In [1]:
import pandas as pd
import glob
from datetime import datetime

In [2]:
files = glob.glob('../sourcedata/*.csv')

In [3]:
dfs = []

In [4]:
for file in files:
    df = pd.read_csv(file)
    dfs.append(df)

In [5]:
combined_df = pd.concat(dfs, ignore_index=True)

In [6]:
len(combined_df)

1239822

In [7]:
combined_df.dropna()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1239817,CE90C772574D5E70,electric_bike,2024-04-21 15:56:52,2024-04-21 16:07:13,Columbus Drive,JC014,Baldwin at Montgomery,JC020,40.718618,-74.038553,40.723659,-74.064194,casual
1239818,70D59D4F56BAA44C,electric_bike,2024-04-21 16:11:20,2024-04-21 16:19:33,Columbus Drive,JC014,Baldwin at Montgomery,JC020,40.718847,-74.038642,40.723659,-74.064194,casual
1239819,919C8DE40AC18B29,electric_bike,2024-04-26 17:48:39,2024-04-26 17:55:20,Columbus Drive,JC014,Baldwin at Montgomery,JC020,40.719039,-74.038610,40.723659,-74.064194,member
1239820,46D5752D4AFF2E1B,classic_bike,2024-04-16 13:20:32,2024-04-16 13:35:39,Columbus Drive,JC014,Baldwin at Montgomery,JC020,40.718355,-74.038914,40.723659,-74.064194,member
1239821,F79D0248A8361A64,electric_bike,2024-04-07 14:11:42,2024-04-07 14:22:13,Columbus Drive,JC014,Baldwin at Montgomery,JC020,40.718823,-74.038696,40.723659,-74.064194,casual

In [8]:
len(combined_df)

1239822

In [9]:
combined_df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [10]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

In [11]:
combined_df.to_csv('../combineddata/combined_citi_bike.csv')